# imports

practicing implementing a transformer with an encoder, a decoder, and an encoder+decoder  

In [13]:
import torch 
import math 
from torch import nn  

print(torch.__version__)

2.1.1


# Positional Encoder Class 

In [26]:
class PositionalEncoder(nn.Module):
    def __init__(self, embedding_size, max_seq_len=512):
        """
        embedding_size == d_model (model dimensions)
        """
        super(PositionalEncoder, self).__init__()
        self.embedding_size = embedding_size
        self.max_seq_len = max_seq_len 
        
        # positional encoder tensor
        pe = torch.zeros(max_seq_len, embedding_size)
        position = torch.arange(0, max_seq_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, embedding_size, 2, dtype=torch.float) * -(math.log(10000.0)/embedding_size))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)
        
    def forward(self, x):
        x = x + self.pe[:, :x.size(1)]
        return x 

In [22]:
z = torch.zeros(4, 8)
print(type(z))
z 

<class 'torch.Tensor'>


tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
z[:, 0::2] = 1
z[:, 1::2] = 2
z

tensor([[1., 2., 1., 2., 1., 2., 1., 2.],
        [1., 2., 1., 2., 1., 2., 1., 2.],
        [1., 2., 1., 2., 1., 2., 1., 2.],
        [1., 2., 1., 2., 1., 2., 1., 2.]])

In [25]:
z[:, :4]

tensor([[1., 2., 1., 2.],
        [1., 2., 1., 2.],
        [1., 2., 1., 2.],
        [1., 2., 1., 2.]])

In [11]:
torch.arange(0, 12, dtype=torch.float).unsqueeze(1)

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.]])

In [16]:
a = torch.arange(0, 8, 2, dtype=torch.float)
print(a)
torch.exp(a)

tensor([0., 2., 4., 6.])


tensor([  1.0000,   7.3891,  54.5982, 403.4288])

In [14]:
math.log(10.)

2.302585092994046

In [20]:
2.718 ** 4

54.575510850575995

In [18]:
2 ** 3

8